[build]
  base = "/"
  publish = "build/"
  command = "npm run build"
  functions = "functions/"

[functions]
  directory = "functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    
[headers.values]
  Access-Control-Allow-Origin = "*"